# Generated by Django 5.0.3 on 2024-04-02 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('block', models.IntegerField(blank=True, null=True)),
                ('office', models.IntegerField(blank=True, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=256)),
                ('account_pic', models.ImageField(blank=True, default='_user/defaults/default_account.png', null=True, upload_to='_user/host_profile_pics')),
                ('host_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.address')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('profile_pic', models.ImageField(blank=True, default='_user/defaults/default_profile.png', null=True, upload_to='_user/user_profile_pics')),
                ('following', models.ManyToManyField(blank=True, to='user.host')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
