# Generated by Django 5.0.3 on 2024-04-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='account_pic',
            field=models.ImageField(blank=True, null=True, upload_to='_user/host_profile_pics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='_user/user_profile_pics'),
        ),
    ]
