# Generated by Django 5.0.3 on 2024-04-05 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_host_user_host_admins_host_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='hosts_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='_user/defaults/default_profile.jpeg', null=True, upload_to='_user/user_profile_pics'),
        ),
    ]
