# Generated by Django 5.0.3 on 2024-04-03 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_hosts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='block',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='office',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_num',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.address'),
        ),
    ]
