# Generated by Django 5.0.3 on 2024-04-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='pass', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='host',
            name='account_pic',
            field=models.ImageField(blank=True, default='_user/defaults/default_account.png', null=True, upload_to='_user/host_profile_pics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, to='user.host'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='_user/defaults/default_profile.png', null=True, upload_to='_user/user_profile_pics'),
        ),
    ]
