# Generated by Django 5.0.3 on 2024-04-05 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_host_admins_alter_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='host_address',
        ),
    ]
