# Generated by Django 5.0.3 on 2024-04-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_is_active_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='defa_uname', max_length=32),
            preserve_default=False,
        ),
    ]
