# Generated by Django 5.0.3 on 2024-04-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_host_host_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='description',
            field=models.TextField(default='Default host description...'),
        ),
    ]
