# Generated by Django 5.0.3 on 2024-04-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_host_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='account_pic',
            field=models.ImageField(default='_user/defaults/default_account.png', upload_to='_user/host_profile_pics'),
        ),
    ]
