# Generated by Django 5.0.3 on 2024-04-08 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_answer_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='question',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
