# Generated by Django 5.0.3 on 2024-04-09 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_answer_host_alter_answer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='downvoted_users',
            field=models.ManyToManyField(blank=True, related_name='downvoted_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='upvoted_users',
            field=models.ManyToManyField(blank=True, related_name='upvoted_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='downvoted_users',
            field=models.ManyToManyField(blank=True, related_name='downvoted_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='upvoted_users',
            field=models.ManyToManyField(blank=True, related_name='upvoted_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
