# Generated by Django 5.0.3 on 2024-04-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_remove_question_author_question_asker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='asker',
        ),
    ]
