# Generated by Django 5.0.3 on 2024-04-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='Default description')),
                ('event_date', models.DateTimeField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ImageField(blank=True, default='_event/defaults/default_poster.png', null=True, upload_to='_event/posters')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
            ],
        ),
    ]
