# Generated by Django 5.0.3 on 2024-03-29 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ImageField(upload_to='event/posters')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('atendees', models.ManyToManyField(to='user.user')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.host')),
            ],
        ),
    ]
