# Generated by Django 5.0.3 on 2024-04-02 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='Default description')),
                ('event_date', models.DateTimeField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ImageField(blank=True, default='_event/defaults/default_poster.png', null=True, upload_to='_event/posters')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('atendees', models.ManyToManyField(blank=True, related_name='users_attending', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_host', to='user.host')),
                ('saved_by', models.ManyToManyField(blank=True, related_name='users_saved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
