# Generated by Django 5.0.3 on 2024-04-01 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('user', '0002_alter_host_account_pic_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='saved_by',
            field=models.ManyToManyField(related_name='users_saved', to='user.user'),
        ),
        migrations.AlterField(
            model_name='event',
            name='atendees',
            field=models.ManyToManyField(related_name='users_attending', to='user.user'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_host', to='user.host'),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='_event/posters'),
        ),
    ]
