# Generated by Django 5.0.3 on 2024-04-03 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='atendees',
            field=models.ManyToManyField(blank=True, related_name='users_attending', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_host', to='user.host'),
        ),
        migrations.AddField(
            model_name='event',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='users_saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
