# Generated by Django 5.0.3 on 2024-04-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_saved_by_alter_event_atendees_and_more'),
        ('user', '0003_alter_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='atendees',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_attending', to='user.user'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='saved_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_saved', to='user.user'),
        ),
    ]
