# Generated by Django 5.0.3 on 2024-04-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notifications',
            field=models.IntegerField(default=0),
        ),
    ]
