# Generated by Django 5.0.3 on 2024-04-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_atendees_alter_event_event_date_and_more'),
        ('user', '0004_user_password_alter_host_account_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='atendees',
            field=models.ManyToManyField(blank=True, related_name='users_attending', to='user.user'),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, default='_event/defaults/default_poster.png', null=True, upload_to='_event/posters'),
        ),
        migrations.AlterField(
            model_name='event',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='users_saved', to='user.user'),
        ),
    ]
