# Generated by Django 5.0.3 on 2024-04-03 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
