# Generated by Django 5.0.3 on 2024-04-05 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_adsress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='adsress',
            new_name='address',
        ),
    ]
