# Generated by Django 5.0.3 on 2024-04-01 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_atendees_alter_event_poster_and_more'),
        ('user', '0004_user_password_alter_host_account_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_host', to='user.host'),
        ),
    ]
