# Generated by Django 5.0.3 on 2024-04-08 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_rename_adsress_event_address'),
        ('user', '0007_alter_host_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_hosted', to='user.host'),
        ),
    ]
